version: '3.8'

services:
  database_sample:
    image: bitnami/postgresql
    restart: always
    container_name: database_sample
    volumes:
      - ./sampleService/src/test.db:/app/test.db
    env_file: ".env"
    ports:
      - 5454:5432 # Remove this on production
    expose:
      - 5432
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USER}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}
      - POSTGRESQL_HOST=${DATABASE_HOST}
      - POSTGRESQL_PORT=${DATABASE_PORT}
  
  sample_service:
    container_name: sample_service
    build: ./sampleService/src
    restart: always
    command: "sh -c 'uvicorn main:app --reload --host 0.0.0.0 --port 8000'"
    volumes:
      - ./sampleService/src:/code
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file: ".env"
    depends_on:
      - database_sample
