name: Sample Service GitHub Actions Demo
run-name: ${{ github.actor }} is testing out SampleService
on: [push]
jobs:
  sampleService:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: launch services
      #   run: |
      #     make sample_run_dev
      - name: launch services
        uses: smartlyio/docker-compose-action@v1
        with:
          composeFile: |
            ./sampleService/docker-compose.testing.yml
          composeArguments: "--env-file=./sampleService/.env.testing"
          
      - name: install PyTest
        run: |
          pip install pytest

      - name: install requirements
        run: |
          pip install -r ./sampleService/src/requirements.txt

      - name: run component tests
        run: |
          make sample_component_tests

      - name: run unit tests
        run: |
          make sample_unit_tests

      - name: stop services
        run: |
          make sample_stop_dev