name: Sample Service GitHub Actions Demo
run-name: ${{ github.actor }} is testing out SampleService
on: [push]
jobs:
  sampleService:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: launch services
        run: |
          make sample_run_dev

      - name: install PyTest
        run: |
          pip install pytest

      - name: install requirements
        run: |
          pip install -r ./sampleService/src/requirements.txt

      - name: DEBUG POSTGRES
        run: |
          PGPASSWORD=pgpswd psql -U admin_tracker -h 0.0.0.0 -p 5454 -d tracker -c "select * from users"

      - name: run component tests
        run: |
          make sample_component_tests

      - name: run unit tests
        run: |
          make sample_unit_tests

      - name: stop services
        run: |
          make sample_stop_dev